# Generated by Django 5.1.6 on 2025-02-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
    ]
